### ISSUE TITLE
Don't depend on 3rd-party packages

### ISSUE THREAD

**Issue by zoechi** [dart-lang/cli_util#10]
https://github.com/dart-lang/test/commit/57355ed7e6067b00d401e5feabfbe95f6b431617#commitcomment-11597295

Seems this prevents this package to be used for its primary use case.

**Comment by pq** [comment]
That comment is inaccurate (and I'll follow up there).  We moved `which` into [dartlang](https://github.com/dart-lang/which) for this very reason.

**Comment by zoechi** [comment]
Thanks for looking into it! 
I would really love to know there is one way to locate the SDK and it is used everywhere. This caused enough troubles in the past.

**Comment by pq** [comment]
> I would really love to know there is one way to locate the SDK and it is used everywhere. This caused enough troubles in the past.

Agreed.  That was exactly the motivation!
