### ISSUE TITLE
Please rename cli_util to something more descriptive.

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/cli_util#11]
cli_util is a super non-descriptive name for a library that only provides a simple, standardized way to get the current SDK directory.

This might give anyone looking through packages the impression that this is something more useful than it is :) The majority of Dart command-line apps is not using the Dart SDK explicitly, I would assume.

**Comment by pq** [comment]
The intention was to grow this library to embrace more general CLI functionality (this was certainly the intent as per https://github.com/dart-lang/cli_util/issues/3).  Nobody's gotten around to it yet though!  I'm open to changing the name though that is a hassle for consumers.  Ideas?

**Comment by BlackHC** [comment]
I was wondering about the same things as in the other thread: what about unscripted? If nothing changes in a couple of months, we could revisit this and decide then? The current name is just a bit confusing with the current state of the library, but if more things were to get added it would make sense ofc.

**Comment by pq** [comment]
A name change isn't planned at the moment; we can re-open if we want to re-visit.
