### ISSUE TITLE
Use a bit more robust _isSdkDir test?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/cli_util#2]
The existence of `bin/dart` would be an equally cheap test, I think.

**Comment by sethladd** [comment]
Would this work even with symlinks?

**Comment by kevmoo** [comment]
You can always resolve symlinks when looking for a file.

**Comment by sethladd** [comment]
Is there a care where the current logic fails?

Or s/robust/simple ?

I'll let @pq take it from here.

**Comment by pq** [comment]
Certainly I think we need some more developed tests.  This code is storied and actually the result of lots of iteration so actually pretty hardened.  We have @devoncarew to thank for that! 

@sethladd : are you worried about anything in particular besides symlinks?  False positives?  False negatives?

Needless to say, test cases are welcome!

**Comment by pq** [comment]
@sethladd: back to the failure case, indeed their was. :)  Patched here: https://github.com/dart-lang/cli_util/pull/4

**Comment by sethladd** [comment]
All props go to @kevmoo

**Comment by pq** [comment]
As we're now using`Platform.environment['DART_SDK']` I think we're pretty good.
